import = ["~/.config/alacritty/catppuccin-mocha.toml"]


[shell]
args = ['--login']
program = "/usr/bin/fish"

[cursor]
style = "Underline"

[font]
size = 13.0

[font.normal]
family = "Fira Code Nerd Font Mono"
#family = "SF Mono"
style = "bold"

[font.offset]
x = 1
y = 0

[window]
startup_mode = "Windowed"
dynamic_padding = true
opacity = 1.0

[window.padding]
x = 30
y = 30

#[window.dimensions]
#columns = 90
#lines = 25


